# Render.yaml - Configuración para despliegue en Render
services:
  - type: web
    name: fraud-simulator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
    healthCheckPath: /
